---
name: Version Bumper
author: Tomer Figenblat
description: Automated semantic version bumps based on conventional commits
branding:
  icon: package
  color: gray-dark
inputs:
  label:
    description: Build label for the development iteration
    required: false
    default: .dev
  changelog:
    description: Set true to create a CHANGELOG.md file
    required: false
    default: false
  preset:
    description: Preset for creating the changelog
    required: false
    default: conventionalcommits
outputs:
  new_version:
    description: The next semantic version
    value: ${{ steps.version-bumper.outputs.new_version }}
  next_dev_iteration:
    description: The next development iteration
    value: ${{ steps.version-bumper.outputs.next_dev_iteration }}
runs:
  using: composite
  steps:
    - id: version-bumper
      shell: bash
      run: ${{ github.action_path }}/action.sh
