---
name: Pull request build

on:
  pull_request_target:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint sources
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_DOCKERFILE: true
          VALIDATE_EDITORCONFIG: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    name: Build docker image
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create initial testing repository
        run: |
          mkdir tmprep
          cd tmprep
          git init
          echo "blabla" > file
          git add file.txt
          git commit -m "build: initial commit"
          git tag -m "1.2.3" 1.2.3

      - name: Add commit of type fix
        run: |
          echo "blabla" > fix_file
          git add fix_file
          git commit -m "fix: fixed something"


      - name: Run action
        uses: ./
