---
name: Pre-Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    environment: staging
    name: Build docker image
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2.3.4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ hashFiles('Dockerfile', '.dockerignore') }}

      - name: Build docker image (no push)
        uses: docker/build-push-action@v2.7.0
        with:
          tags: tomerfi/version-bumper-action:early-access
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          load: true

      - name: Delete docker image
        run: docker image rm tomerfi/version-bumper-action:early-access
